export enum UploadTypesEnum {
  DOCUMENT = 'document',
  IMAGE = 'image',
  FILE = 'file',
}

export const UPLOAD_TYPE_ALLOWED_EXTENSIONS: Record<UploadTypesEnum, string[]> =
  {
    [UploadTypesEnum.DOCUMENT]: [
      'pdf',
      'doc',
      'docx',
      'xls',
      'xlsx',
      'ppt',
      'pptx',
      'txt',
      'csv',
    ],
    [UploadTypesEnum.IMAGE]: [
      'jpg',
      'jpeg',
      'png',
      'gif',
      'bmp',
      'svg',
      'webp',
      'ico',
    ],
    [UploadTypesEnum.FILE]: [
      'pdf',
      'doc',
      'docx',
      'xls',
      'xlsx',
      'ppt',
      'pptx',
      'txt',
      'csv',
      'json',
      'xml',
      'zip',
      'rar',
      '7z',
      'jpg',
      'jpeg',
      'png',
      'gif',
      'bmp',
      'svg',
      'webp',
      'ico',
      'mp4',
      'avi',
      'mov',
      'wmv',
      'flv',
      'webm',
      'mp3',
      'wav',
      'ogg',
      'm4a',
    ],
  };
