export enum EventName {
  USER_REGISTERED = 'user.registered',
  USER_INVITED = 'user.invited',
  USER_INVITE_RESENT = 'user.invite_resent',
  USER_INVITE_ACCEPTED = 'user.invite_accepted',
  USER_CREATED = 'user.created',
  USER_BLOCKED = 'user.blocked',
  USER_UNBLOCKED = 'user.unblocked',
  USER_PASSWORD_RESET_REQUESTED = 'user.password_reset_requested',
  USER_PASSWORD_RESET = 'user.password_reset',
  USER_PASSWORD_UPDATED = 'user.password_updated',
  USER_LOGGED_IN = 'user.logged_in',
  USER_LOGGED_OUT = 'user.logged_out',
  ORGANIZATION_CREATED = 'organization.created',
  ROLE_CREATED = 'role.created',
  ROLE_UPDATED = 'role.updated',
  ROLE_DELETED = 'role.deleted',
  APPLICATION_CREATED = 'application.created',
  APPLICATION_STATUS_CHANGED = 'application.status_changed',
  APPLICATION_ASSIGNED = 'application.assigned',
}
